global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "users_service"
    static_configs:
      - targets: ["users_service:5000"]

  - job_name: "items_service"
    static_configs:
      - targets: ["items_service:5001"]
